# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MainUser\Desktop\tech_groupproject\school-management-system\sign\login_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.enter_Button = QtWidgets.QPushButton(Form)
        self.enter_Button.setGeometry(QtCore.QRect(260, 190, 56, 17))
        self.enter_Button.setObjectName("enter_Button")
        self.email_label = QtWidgets.QLabel(Form)
        self.email_label.setGeometry(QtCore.QRect(80, 90, 71, 21))
        self.email_label.setMaximumSize(QtCore.QSize(150, 100))
        self.email_label.setObjectName("email_label")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setGeometry(QtCore.QRect(80, 140, 71, 21))
        self.password_label.setMaximumSize(QtCore.QSize(150, 100))
        self.password_label.setObjectName("password_label")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(150, 140, 113, 20))
        self.password.setMaxLength(8)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.email = QtWidgets.QLineEdit(Form)
        self.email.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.email.setObjectName("email")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.enter_Button.setText(_translate("Form", "Enter"))
        self.email_label.setText(_translate("Form", "E-mail Adress:"))
        self.password_label.setText(_translate("Form", "Password:"))
