# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MainUser\Desktop\tech_groupproject\school-management-system\sign\signup_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(150, 40, 113, 20))
        self.name.setObjectName("name")
        self.surname = QtWidgets.QLineEdit(Form)
        self.surname.setGeometry(QtCore.QRect(150, 70, 113, 20))
        self.surname.setObjectName("surname")
        self.city = QtWidgets.QLineEdit(Form)
        self.city.setGeometry(QtCore.QRect(150, 130, 113, 20))
        self.city.setObjectName("city")
        self.email = QtWidgets.QLineEdit(Form)
        self.email.setGeometry(QtCore.QRect(150, 160, 113, 20))
        self.email.setObjectName("email")
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(80, 40, 61, 21))
        self.name_label.setObjectName("name_label")
        self.surname_label = QtWidgets.QLabel(Form)
        self.surname_label.setGeometry(QtCore.QRect(80, 70, 61, 21))
        self.surname_label.setObjectName("surname_label")
        self.birth_label = QtWidgets.QLabel(Form)
        self.birth_label.setGeometry(QtCore.QRect(80, 100, 51, 21))
        self.birth_label.setObjectName("birth_label")
        self.email_label = QtWidgets.QLabel(Form)
        self.email_label.setGeometry(QtCore.QRect(80, 160, 51, 21))
        self.email_label.setObjectName("email_label")
        self.city_label = QtWidgets.QLabel(Form)
        self.city_label.setGeometry(QtCore.QRect(80, 130, 61, 21))
        self.city_label.setObjectName("city_label")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setGeometry(QtCore.QRect(80, 189, 61, 21))
        self.password_label.setObjectName("password_label")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(150, 190, 111, 20))
        self.password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password.setMaxLength(8)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.repassword = QtWidgets.QLineEdit(Form)
        self.repassword.setGeometry(QtCore.QRect(150, 220, 113, 20))
        self.repassword.setMaxLength(8)
        self.repassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repassword.setObjectName("repassword")
        self.re_password_label = QtWidgets.QLabel(Form)
        self.re_password_label.setGeometry(QtCore.QRect(80, 225, 51, 21))
        self.re_password_label.setObjectName("re_password_label")
        self.sign_Button = QtWidgets.QPushButton(Form)
        self.sign_Button.setGeometry(QtCore.QRect(200, 250, 56, 21))
        self.sign_Button.setObjectName("sign_Button")
        self.birthday = QtWidgets.QDateEdit(Form)
        self.birthday.setGeometry(QtCore.QRect(150, 100, 110, 22))
        self.birthday.setObjectName("birthday")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", "Name"))
        self.surname_label.setText(_translate("Form", "Surname"))
        self.birth_label.setText(_translate("Form", "Birthday"))
        self.email_label.setText(_translate("Form", "Email"))
        self.city_label.setText(_translate("Form", "City"))
        self.password_label.setText(_translate("Form", "Password"))
        self.re_password_label.setText(_translate("Form", "Re-Password"))
        self.sign_Button.setText(_translate("Form", "Sign"))
